Update workflow file

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -34,6 +34,16 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
+	      - name: Check Docker Hub credentials
+        run: |
+          if [ -z "${{ secrets.REGISTRY_USER }}" ] || [ -z "${{ secrets.REGISTRY_TOKEN }}" ]; then
+            echo "ERROR: REGISTRY_USER or REGISTRY_TOKEN is empty. Add them under Settings → Secrets → Actions."
+            exit 1
+          else
+            echo "Registry user: ${{ secrets.REGISTRY_USER }}"
+          fi
+
+
       - name: Build Docker image
         run: |
           docker build -t ${{ secrets.REGISTRY_USER }}/simple-app:${{ github.sha }} ./simple-app
